- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/emitirParecer.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/funcoes.js
Iclusão da tela de confirmação na emissão de parecer
> 1699 incluir confirmacao de emissao de parecer

- aplicacoes/gpa/pom.xml
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/applnConfig.xml
- aplicacoes/gpa/src/main/webapp/WEB-INF/jasper-views.xml
Adicionei os xmls necessários para os relatórios
> 1833 emitir relatorios projetos por docente

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/modulos/footer.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/cadastrar.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/jquery.MultiFile.js
Permitir anexar múltiplos arquivos de diferentes pastas já na tela de
> [UI] Permitir incluir múltiplos anexos de pastas diferentes na edição do projeto

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/PessoaController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/ProjetoService.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/ProjetoServiceImpl.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/diretor/detalhesUsuario.jsp
> #2101 uc13 visualizar informações de usuarios

- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Remove opções de ordenação na coluna de Data Avaliação
Inclui opção de ordenação na coluna de Status.
> Remove opções de ordenação de colunas na aba Avaliados

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/participante.jsp
Adiciona abas com título responsivo.
Permite acessar abas específicas via URL.
> Ajusta página com informações de participantes.

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/participacoes.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Inversão da listagem dos participantes com o formulário. Alteração no controller para passar o ano atual. Adição das funcionalidades do dataTables para a tabela.
> #2439 página ajustada com datatables

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/index.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Remover opção de ordenação das colunas de datas.
Incluir opção de ordenação nas demais colunas.
> 2443 remover opçao de ordenacao

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
> adição de opção de inclusão de participantes na tela de detalhes do

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/modulos/footer.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/avaliar-projeto-validator.js
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
> #2511 alteração na mensagem de obrigatoriedade de Ata de reunião e

- aplicacoes/gpa/pom.xml
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
- Remoção da descrição duplicada.
- Atualização do groupId/artifactId biblioteca Jackson.
> 2504 descricao projeto duplicada

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/PessoaController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/participante.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Persiste abas selecionadas utilizando URL como referência.
> Ajustar a atualização da página de projetos

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/observer/EmailObserver.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/ProjetoServiceImpl.java
O envio de email continua desabilitado por default.
> 2542 funcionamento envio notificacoes

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/participacoes.jsp
- Ajusta posição dos controles utilizando grids nos detalhes dos projetos.
- Exibe Início/Término do projeto na janela de adicionar participantes.
- Ajusta tamanho dos botões no modal de exclusão de participantes.
> 2544 ajustar botao modal acao participante

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/PessoaController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/ProjetoService.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/ProjetoServiceImpl.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/participante.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
- Projetos que coordena:
Deve ser exibida lista projetos em andamento (que já foram aprovados ou aprovados com restrição e estão dentro do período de duração) que o usuário coordena.
- Projetos que participa:
Deverão aparecer apenas projetos que estão dentro do período de duração e que o usuário não seja autor do projeto.
- Projetos que coordenou:
Deverão ser exibidos apenas projeto que foram aprovados ou aprovados com restrição e que o período de duração do projeto já tenha passado.
- Projetos que participou:
Deverão aparecer apenas projetos que o período de duração do projeto já tenha passado, que tenham sido aprovados ou aprovados com restrição e que o usuário não seja autor do projeto.
> 2586 ajustar informacoes projetos participante

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/administracao/index.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/buscar-participante.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
> #2630 Inclusão de datatables para ordenação dos usuários nas buscas da

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/relatorios.jsp
> ajuste da exibição das datas nos relatórios dos projetos reprovados e

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/relatorios.jsp
> Melhorias diversas pagina relatorios

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/cadastrar.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/participacoes.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
participantes, melhoria no botão de cancelar tela de cadastro de
projeto.
> Adição de funcionalidade de voltar na tela de vinculação de

- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Não criei outro branch, pequena alteração apenas
> #2724 melhoria migrar dependencias pom

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/DocumentoServiceImpl.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/utils/Constants.java
caminho do arquivo compativel com windows e linux
> 2807 alterar o modo de salvar aquivos

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/cadastrar.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/listar.jsp
datas de inicio e termino estivem preenchidas
> Modificação para permitir a vinculação de participante somente quando as

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/validation/ProjetoValidator.java
- aplicacoes/gpa/src/main/resources/WEB-INF/messages_pt_BR.properties
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/cadastrar.jsp
periodos diferentes das participações já cadastradas.
> As datas de inicio e termino e um projeto não podem ser alteradas para

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/ProjetoService.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/DocumentoServiceImpl.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/ProjetoServiceImpl.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/listar.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
> Mostrar visualização da lista de projetos com parecer emitido pelo

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/model/Projeto.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/utils/Constants.java
Método adicionarParticipacao() foi aproveitado e melhorado.
> Participações alterada em Projeto sem uso do método setParticipações.

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/model/Pessoa.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/ParticipacaoService.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/DocumentoServiceImpl.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/PessoaServiceImpl.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/submeter.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Melhorias em código realizadas de acordo com o codacy
> Melhorias feitas de acordo com o Codacy

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
Botão para upload de arquivos adicionado. Coordenador, o parecerista, o relator e a direção podem fazer upload de arquivos a qualquer momento.
> PESQ-16: Botão para upload de arquivos adicionado. Coordenador, o

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/DirecaoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/model/Log.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/model/Projeto.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/observer/EmailObserver.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/observer/LogObserver.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/Observer.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/ProjetoService.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/NotificacaoService.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/ProjetoServiceImpl.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/applicationContext.xml
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
Criação de logs:
criação da entida LOG
configuração da persistência da  entidade
alterações nos controladores do projeto e diretor
alteração na página de detalhes
> Pesq 26 fazer log alteracoes

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/DirecaoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/impl/PessoaServiceImpl.java
evitando fazer outra busca no banco.
A busca em getPessoa foi melhorada, no lugar de buscar uma lista de
pessoas para então retornar o primeiro, agora ele busca somente pela
primeira ocorrência.
> O metodo setInfoDocumentos agora recebe uma pessoal no lugar do cpf,

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/service/validation/ProjetoValidator.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/submeter.jsp
remoção do campo valor duplicado em submeter
> fonte de financiamento obrigatoria na submissao

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/listar.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
atualização na listar do coordenador
> Atualização da página listar do coordenador

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/cadastrar.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Adicionado listagem de anexos na pagina editar projeto.
adicionado botão que redireciona para a pagina de upload.
> Pesq 62 adicionar listagem e botao anexos ao editar

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/participacoes.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
> Pesq melhorias correcoes

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/homologar-projeto.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/submeter.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Mostra lista de fonte de financiamento quando o projeto é submetido com
erros
correção capo mês em cadastrar participantes.
correções layout em detalhes de projeto e na pagina de homologação
> Mostrar obrigatoriedade do arquivo de projeto ao submeter.

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/homologar-projeto.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/cadastrar.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/emitir-parecer-tecnico.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/emitir-relatorio.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/submeter.jsp
removendo o drag and drop dos campos de upload
> Pesq 67 remover opção de drag and drop dos campos de upload

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/homologar-projeto.jsp
Pesq 73 mostrar parecer relator homologar pagina
> Pesq 73 mostrar parecer relator homologar pagina

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/GPAController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/modulos/footer.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/sobre.jsp
> Nova view com nome e email de todas as pessoas que contriburam para o

- aplicacoes/gpa/src/main/java/ufc/quixada/npi/gpa/controller/ProjetoController.java
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/emitir-parecer-relator.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/listar.jsp
Para implementar esta funcionalidade, foram feitas modificações na
página de listar projetos (aba de avaliação), na página de emitir
parecer do relator, e no método "AvaliarForm" na classe
"ProjetoController".
> PESQ-72 Permitir atualização do parecer do relator

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/atribuir-parecerista.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/direcao/atribuir-relator.jsp
- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/participacoes.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
> Usar select2 nas selects para permitir filtrar resultados pelo valor da

- aplicacoes/gpa/src/main/webapp/WEB-INF/view/projeto/detalhes.jsp
- aplicacoes/gpa/src/main/webapp/resources/js/gpa.js
Foi implementada a funcionalidade de visualizar o status do projeto na
página de detalhes do projeto.
> PESQ-29 Criar visualização do status do projeto
